### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by HKWO** [Gork3m/filesecuring-xor-unpacker#1]
can u help me to decrypt this script?
[Messaged.txt](https://github.com/Gork3m/filesecuring-xor-unpacker/files/8494322/Messaged.txt)

**Comment by Gork3m** [comment]
As soon as I see a sentence starting with "can u help", my gag reflex prevents me from reading the rest of it.

**Comment by HKWO** [comment]
pls im need ur help
