### ISSUE TITLE
YEY

### ISSUE THREAD

**Issue by nucleousV** [Gork3m/filesecuring-xor-unpacker#2]

**Comment by Gork3m** [comment]
Send file

**Comment by nucleousV** [comment]
[Tested.zip](https://github.com/Gork3m/filesecuring-xor-unpacker/files/9776972/Tested.zip)
Ex that i use

**Comment by Gork3m** [comment]
It fails to catch because original script is too small. You must obfuscate a larger script (just like how you would normally find in the nature).

**Comment by nucleousV** [comment]
> (just

so its impossible to do small ones? thanks :D

**Comment by Gork3m** [comment]
no its not impossible but I'm too lazy to add support for it. This currently compares the script size to the fake ones in obfuscated script. If its smaller than them, it will fail but its like a 3 line fix

**Comment by nucleousV** [comment]
ah okay thanks for helping xD this the best deobf so far :3 and free 

but when meet the small original script its hard for me to skid now hahaha
